-- plugins
require("plugins.init")
require("plugins.blink-cmp")
require("plugins.bufferline")
require("plugins.cmdline")
require("plugins.dashboard")
require("plugins.fzf")
require("plugins.git")
require("plugins.mason")
require("plugins.go")
require("plugins.lsp")
require("plugins.themes")
require("plugins.treesitter")
require("plugins.mini.cursorword")
require("plugins.mini.files")
require("plugins.mini.icons")
require("plugins.mini.move")
require("plugins.mini.notify")
require("plugins.mini.pairs")
require("plugins.mini.pick")
require("plugins.mini.sessions")

-- .
require("autocmd")
require("options")
require("keymap")
